### ISSUE TITLE
Please ensure the the project builds from a fresh clone. 

### ISSUE THREAD

**Issue by rennarda** [georgeglint/astro#1]
I tried to build the project but got the following error: 

```
ld: framework not found Pods_Astro
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Please ensure the project builds correctly - if there are any steps required to get this to work, please document them. 

Thanks..

**Comment by georgeglint** [comment]
Hi Andy,

Please use `Astro.xcworkspace` to launch the project. Apologies for not leaving installation instructions - I have updated the [README.md](https://github.com/georgeglint/astro/blob/main/README.md) to reflect this.

If there are any issues please let me know.

**Comment by rennarda** [comment]
Thanks George, I completely overlooked the .xcworkspace file. It's working now.

**Comment by georgeglint** [comment]
Great, thank you! Apologies again it was an oversight on my part.
